"""Initial migration

Revision ID: ee33a91f5816
Revises: 
Create Date: 2024-10-14 02:34:15.998630

"""
from pathlib import Path
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee33a91f5816'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodstuffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodstuffs_id'), 'foodstuffs', ['id'], unique=False)
    # ### end Alembic commands ###

    with Path('scripts/foodstuffs.sql').open('r', encoding='utf-8') as f:
        sql_script = f.read()

    op.execute(text(sql_script))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foodstuffs_id'), table_name='foodstuffs')
    op.drop_table('foodstuffs')
    # ### end Alembic commands ###
